#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/asapci/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle..."
    brew bundle --global
  fi
  brew install yadm
  source .zprofile
  yadm clone -b Darwin https://github.com/bo1929/bodot.git
  yadm bootstrap
  source .zshrc
  git config --global pull.rebase true
  alacritty migrate
  GPG_TTY=$(tty)
  export GPG_TTY
  yadm decrypt
fi
