#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI2 -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a firefox desktop=^10, follow=on
bspc rule -a Spotify desktop=^9, follow=on

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
# Preventing duplicate processes
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
  touch $startup_lock_file
  dunst &
  nitrogen --restore &
  picom -CGb &
  xset s off &
  xset r rate 220 45 &
  xset s off -dpms & # Do not susped.
  setxkbmap -option caps:escape &
  xsetroot -cursor_name left_ptr &
  dex -a -s /etc/xdg/autostart/:${HOME}/.config/autostart/ &
  ${HOME}/.screenlayout/monitor.sh &
  ${HOME}/.config/bspwm/scripts/low_battery_notifier.sh &
  # Color-temperature based on location.
    # İstanbul 41.01384:28.94966
    # San Diego 32.7157:117.1611
    # Denizli 37.7830:29.0963
  redshift -Pl 32.7157:-117.1611 &
fi
